version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - recipe

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_NUM_PARTITIONS: 1
      KAFKA_NUM_PARTITIONS: 3

#      KAFKA_HEAP_OPTS: "-Xmx512m -Xms256m"
#      KAFKA_JVM_PERFORMANCE_OPTS: "-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20"
#
#      # 로그 유지 최적화
#      KAFKA_LOG_RETENTION_HOURS: 1
#      KAFKA_LOG_SEGMENT_BYTES: 52428800
#      KAFKA_LOG_RETENTION_BYTES: 52428800
#
#        # Consumer Group 설정 (리밸런싱 방지)
#      KAFKA_GROUP_INITIAL_BALANCE_DELAY_MS: 5000
#      KAFKA_OFFSETS_RETENTION_MINUTES: 30

    depends_on:
      - zookeeper
    networks:
      - recipe
#    deploy:
#      resources:
#        limits:
#          memory: 512M
    restart: always

#  recipe-app:
#    image: recipe-app:0.0.1
#    container_name: recipe
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    depends_on:
#      - kafka
#    networks:
#      - recipe

networks:
  recipe:
    driver: bridge